import etnik from '../images/kadin/ethnic.webp';
import greendress from '../images/kadin/greendress.webp';
import micky from '../images/kadin/micky.jpeg';
import tunic from '../images/kadin/tunic.webp';
import white from '../images/kadin/white.webp';

import blue from "../images/erkek/blue.jpg";
import clas from "../images/erkek/clas.webp";
import deri from "../images/erkek/deri.jpg";
import kot from "../images/erkek/kot.jpg";
import pantolon from "../images/erkek/pantolon.jpg";

import beyaz from "../images/cocuk/beyaz.webp";
import minecraft from "../images/cocuk/minecraft.jpg";
import mor from "../images/cocuk/mor.webp";
import pile from "../images/cocuk/pile.jpg";
import siyah from "../images/cocuk/siyah.jpg";


const data = {
    productItems:[
        {
            id: "1",
            ad: "Etnik Desenli Elbise",
            exprice: "1000",
            price: "600",
            image: etnik,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "2",
            ad: "Yeşil Uzun Elbise",
            exprice: "1500",
            price: "899.9",
            image: greendress,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "3",
            ad: "Micky Mouse Tişört",
            exprice: "1120",
            price: "650",
            image: micky,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "4",
            ad: "Arkası Desenli Elbise",
            exprice: "1200",
            price: "699.9",
            image: tunic,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "5",
            ad: "Beyaz Uzun Elbise",
            exprice: "800",
            price: "710",
            image: white,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "6",
            ad: "Etnik Desenli Elbise 2",
            exprice: "1000",
            price: "600",
            image: etnik,
            isInCart: false,
        },
        {
            id: "7",
            ad: "Yeşil Uzun Elbise 2",
            exprice: "1500",
            price: "899.9",
            image: greendress,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "8",
            ad: "Micky Mouse Tişört 2",
            exprice: "1120",
            price: "650",
            image: micky,
            isInCart: false,
        },
        {
            id: "9",
            ad: "Arkası Desenli Elbise 2",
            exprice: "1200",
            price: "699.9",
            image: tunic,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "10",
            ad: "Beyaz Uzun Elbise 2",
            exprice: "800",
            price: "710",
            image: white,
            isFavorite: false,
            isInCart: false,
        },
    ],
    productItemsErkek: [
        {
          id: "11",
          ad: "Mavi Tişört",
          exprice: "1000",
          price: "600",
          image: blue,
          isFavorite: false,
          isInCart: false,
        },
        {
          id: "12",
          ad: "Takım Elbise",
          exprice: "1500",
          price: "899.9",
          image: clas,
          isFavorite: false,
          isInCart: false,
        },
        {
            id: "13",
            ad: "Deri Ceket",
            exprice: "1500",
            price: "925",
            image: deri,
            isFavorite: false,
            isInCart: false,
          },
          {
            id: "14",
            ad: "Kot Ceket",
            exprice: "820",
            price: "800",
            image: kot,
            isFavorite: false,
            isInCart: false,
          },
          {
            id: "15",
            ad: "Pantolon",
            exprice: "750",
            price: "700",
            image: pantolon,
            isFavorite: false,
            isInCart: false,
          },
          {
            id: "16",
            ad: "Mavi Tişört 2",
            exprice: "1000",
            price: "600",
            image: blue,
            isFavorite: false,
            isInCart: false,
          },
          {
            id: "17",
            ad: "Takım Elbise 2",
            exprice: "1500",
            price: "925",
            image: clas,
            isFavorite: false,
            isInCart: false,
          },
          {
              id: "18",
              ad: "Deri Ceket 2",
              exprice: "1250",
              price: "1200",
              image: deri,
              isFavorite: false,
              isInCart: false,
            },
            {
              id: "19",
              ad: "Kot Ceket 2",
              exprice: "820",
              price: "800",
              image: kot,
              isFavorite: false,
              isInCart: false,
            },
            {
              id: "20",
              ad: "Pantolon 2",
              exprice: "750",
              price: "700",
              image: pantolon,
              isFavorite: false,
              isInCart: false,
            },

      ],
      productItemsCocuk:[
        {
            id: "21",
            ad: "Beyaz Tişört",
            exprice: "680",
            price: "600",
            image: beyaz,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "22",
            ad: "Mor Elbise",
            exprice: "920",
            price: "860",
            image: mor,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "23",
            ad: "Minecraft Tişört",
            exprice: "720",
            price: "680",
            image: minecraft,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "24",
            ad: "Beyaz Elbise",
            exprice: "980",
            price: "950",
            image: pile,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "25",
            ad: "Siyah Tişört",
            exprice: "660",
            price: "599",
            image: siyah,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "26",
            ad: "Beyaz Tişört 2",
            exprice: "680",
            price: "600",
            image: beyaz,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "27",
            ad: "Mor Elbise 2",
            exprice: "920",
            price: "860",
            image: mor,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "28",
            ad: "Minecraft Tişört 2",
            exprice: "720",
            price: "680",
            image: minecraft,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "29",
            ad: "Beyaz Elbise 2",
            exprice: "980",
            price: "950",
            image: pile,
            isFavorite: false,
            isInCart: false,
        },
        {
            id: "30",
            ad: "Siyah Tişört 2",
            exprice: "660",
            price: "599",
            image: siyah,
            isFavorite: false,
            isInCart: false,
        },
      ]
};

export default data; //export etmeyi unutma!!